{% set name = "Willow" %}
{% set version = "1.5" %}
{% set sha256 = "3fe42cda9872d8e4f64df301e58a1d8be5b9e66944eb83aadcc50128d3ae658a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - filetype >=1.0.10,!=1.1.0
    - defusedxml >=0.7,<1.0

test:
  imports:
    - willow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail/Willow
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A unified interface to Python image libraries
  description: |
    Willow is a simple image library that combines the APIs of Pillow,
    Wand and OpenCV. It converts the image between the libraries when
    necessary.
  doc_url: http://willow.readthedocs.io/en/latest/
  dev_url: https://github.com/wagtail/Willow

extra:
  recipe-maintainers:
    - darynwhite
    - cshaley
    - sannykr
